type: "simulstream.server.speech_processors.canary_sliding_window_retranslation.CanarySlidingWindowRetranslator"
model_name: "nvidia/canary-1b-v2"
detokenizer_type: "canary"
window_len: 12
matching_threshold: 0.1